/*

This file is part of Streembit application. 
Streembit is an open source communication application. 

Streembit is a free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
as published by the Free Software Foundation, either version 3.0 of the License, or (at your option) any later version.

Streembit is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Streembit software.  
If not, see http://www.gnu.org/licenses/.
 
-------------------------------------------------------------------------------------------------------------------------
Author: Streembit development team
Copyright (C) Streembit 2017
-------------------------------------------------------------------------------------------------------------------------

*/

import i18next from 'i18next';

// TODO get this from a resource files based on the language
var ErrorCodes = {
    "en": {

    }
};

export default function () {
    return new Promise((resolve, reject) => {
        i18next.init({
            lng: 'en',
            resources: {
                en: {
                    translation: {                        
                        "appname-title": "Streembit",
                        "appname-sub-title": "Decentralized, peer-to-peer communication system for humans and machines",
                        "appload-streembit": "Load Streembit",
                        "appload-application": "Load application",
                        "appload-components": "Loading UI components",
                        "appload-datadir": "Create application data directory",
                        "appload-databind": "Create data binders",
                        "appload-database": "Load database",
                        "appload-logger": "Creating application logger",
                        "appload-settings": "Load settings from local database",
                        "appload-accounts": "Load accounts from local database",
                        "appload-apputils": "Create application utility handler",
                        "appload-contacts": "Load contacts from local database",
                        "appload-contact-handler": "Initialize contacts handler",
                        "appload-events": "Create event handlers",
                        "appload-kademlia": "Load Kademlia DHT",
                        "appload-streembitconn": "Connecting to the Streembit P2P network",
                        "appload-complete": "Application resource loading has been completed",
                        "lbl-initui-connect": "Connect",
                        "lbl-initui-newaccount": "New Account",
                        "lbl-initui-initexisting": "Initialize Existing Account",
                        "lbl-initui-restore": "Restore Account",
                        "lbl-createaccount-create": "Create new Streembit account",
                        "lbl-connectto-public-net": "Initialize Streembit account",
                        "lbl-connect": "Connect",
                        "lbl-submit": "Submit",
                        "lbl-streembitacc": "Streembit account",
                        "lbl-saved-accounts": "Saved accounts",
                        "lbl-privkeypassword": "Private key password",
                        "lbl-confirmpassword": "Confirm private key password",
                        "lbl-changepwd-title": "Change your Streembit password",
                        "lbl-changepwd-change": "Change password",
                        "errmsg-createaccount-accountname": "The account name must be between 6-20 characters and it can only contain alphanumeric characters (letters a-z, A-Z and numbers 0-9)",
                        "errmsg-createaccount-exists": "The account already exists in your account list.",
                        "errmsg-createaccount-pwdrequired": "Password is required",
                        "errmsg-createaccount-pwdlength": "The password must be at least 8 characters",
                        "errmsg-createaccount-nospaceallowed": "The password must not contain empty space",
                        "errmsg-createaccount-lowercaseneed": "The password must contain at least one lower case letter",
                        "errmsg-createaccount-uppercaseneed": "The password must contain at least one upper case letter",
                        "errmsg-createaccount-digitneed": "The password must contain at least one digit",
                        "errmsg-createaccount-specialcharneed": "The password must contain at least one special character",
                        "errmsg-createaccount-pwdconfirm": "Password confirm input value is required",
                        "errmsg-createaccount-pwdconfirmmatch": "The password and its confirm are not the same",
                        "errmsg-connectaccount-select": "Select an account from the saved account list",
                        "appmsg-nopeer-wsuseprompt": "Unable to connect via the TCP peer connection. Most likely your firewall, port forwarding or UPnP configuration is blocking the communication via TCP.\nWould you like to use WebSocket connection? Your signalling and contact discovery will be performed by a WebSocket server, but your video, audio, text communication and file sending will still be fully encrypted and peer-to-peer.",
                        "appmsg-askwspublish": "Would you like to publish data to Streembit WebSocket hubs? Using WebSocket enables communication with users who are unable to etablish a TCP connection. Using WS signalling your video, audio, text communication and file sending will still be fully encrypted and peer-to-peer.",
                        "errmsg-wallet-send-recipient": "Recipient is a string 30-40 chars long. no blanks, no special chars",
                        "errmsg-wallet-send-amount": "Amount is not empty, can be a floating",
                        "errmsg-wallet-send-fees": "Fees is not empty, can be a floating",
                        "errmsg-wallet-receive-message": "Message contains chars that we do not accept",
                        "errmsg-wallet-receive-label": "Label contain unacceptable characters",
                        "errmsg-transport-send": "There is an error processing your request. Please, try again later",
                        "lbl-restore-account": "Restore Account",
                        "lbl-restore-backup": "Restore from Backup",
                        "ttlbtn-restore-mnemonic": "Restore from Mnemonic",
                        "btn-hide-restore-mnemonic": "Hide mnemonic field",
                        "sbm-restore-mnemonic": "Restore",
                        "lbl-mnemonic": "Mnemonic",
                        "lbl-restore-mnemonic": "Restore private key from Mnemonic",
                        "errmsg-remnemonic-invalid": "Invalid mnemonic",
                        "errmsg-remnemonic-validation-failed": "Mnemonic validation failed. Check spelling and wording",
                        // view titles
                        "view-title-dashboard": "Dashboard",
                        "view-title-help": "Help",
                        "view-title-settings": "Settings",
                        "view-title-netinfo": "Account, network info",
                        "view-title-logs": "Logs",
                        "view-title-certificates": "X.509 certificates",
                        "view-title-utilcerts": "Utility certificates",
                        "view-title-commsecurity": "Communication security",
                        "view-title-addiothub": "Add IoT Hub",
                        "view-title-devices": "My Devices",
                        "view-title-wallet": "Wallet",
                        "view-title-balance": "Balance",
                        "view-title-contact": "Contact details",
                        "view-title-contact-chat": "Text chat",
                        "view-title-audio-call": "Audio Call",
                        "view-title-offline-contact-request": "Create offline contact offer",
                        "view-title-accept-contact-request": "Add contact",
                        "view-title-my-contacts": "My contacts",
                        "wal-dinamic-fees": "Use dynamic fees",
                        "wal-fees-manually": "Edit fees manually",
                        "wal-propose-replace": "Propose Replace-By-Fee:",
                        "wal-fee-unit": "Fee Unit:",
                        "wal-change-address": "Use change addresses",
                        "wal-multiple-change-address": "Use multiple change addresses",
                        "wal-coin-section": "Coin Section",
                        "wal-confirmed-coins": "Spend only confirmed coins",
                        "wal-language" : "Language:",
                        "wal-decimal-point": "Zeros after decimal point:",
                        "wal-base-unit": "Base unit",
                        "wal-currency": "Fiat currency",
                        "wal-history-rates": "Show history rates",
                        "wal-fiatBalance-address": "Show fiat balance for addresses",
                        "wal-open-alias": "Open Alias:",
                        "wal-ssl-certificate": "SSL certificate:",
                        "col-balance": "Balance",
                        "col-recent-transactions": "Recent transactions",
                        "col-appearance" : "Appearance",
                        "col-fiat": "Fiat",
                        "col-identity": "Identity",
                        "tab-payTo": "Pay To:",
                        "tab-label": "Label:",
                        "tab-amount": "Amount:",
                        "tab-address": "Address",
                        "tab-transaction-fees": "Transaction Fees",
                        "tab-SBCoin": "SBCoin/kB",
                        "tab-request-replace-be-fee": "Request replace be Fee",
                        "btn-clear": "Clear",
                        "btn-copy-uri": "Copy URI",
                        "btn-copy-address": "Copy Address",
                        "btn-save-image": "Save Image",
                        "btn-close": "Close",
                        "tab-message": "Message",
                        "tab-request-payment-history": "Requested Payment History",
                        "tb-header-text-date": "Date",
                        "tb-header-text-address": "Address",
                        "tb-header-test-label": "Label",
                        "tb-header-amount-req": "Amount",
                        "tb-header-amount-tranc": "Amount Transacted (SBCoin)",
                        "tb-header-type": "Type",
                        "tb-header-balance": "Balance",
                        "nav-overview": "Overview",
                        "nav-send-money": "Send Money",
                        "nav-receive-money": "Receive Money",
                        "nav-transactions": "Transactions",
                        "coin-name": "SBCoin",
                        "mainMenuFile": "File",
                        "delete": "Delete",
                        "backup": "Backup",
                        "menu-title-security": "Security",
                        "menu-title-actions": "Actions",
                        "menu-item-restore-wallet": "Restore wallet",
                        "menu-item-backup-wallet": "Backup wallet",
                        "menu-item-delete-wallet": "Delete wallet",
                        "menu-item-password": "Password",
                        "menu-item-seed": "Seed",
                        "menu-item-private-keys": "Private keys",
                        "menu-item-history": "Export history",
                        "menu-title-settings": "Settings",
                        "menu-item-contract": "Create smart contract",
                        "menu-item-preferences": "Preferences",
                        "menu-item-network": "Network",
                        "menu-item-sign-message": "Sign message",
                        "menu-item-verify-message": "Verify message",
                        "menu-item-encrypt": "Encrypt",
                        "menu-item-load-transaction": "Load transaction",
                        "menu-item-from-text": "from text",
                        "menu-item-from-blockchain": "from blockchain",
                        "menu-item-qr-code": "from QR code",
                        "menu-item-documentation": "Documentation",
                        "password-item-title": "Your wallet is password protected and encrypted.Use this dialog to change the password.",
                        "text": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
                        "delete-text": "You are about to delete a and all of its contents.",
                        "deleteOp": "This operation is permanent and cannot be undone.",
                        "passworddialog": "Your wallet is password protected and encrypted.Use this dialog to change the password.",
                        "currentpass": "Current Password:",
                        "newpassword": "New Password:",
                        "confirmpass": "Confirm Password:",
                        "enterpass" : "Please enter your password",
                        "next-button": "Next",
                        "col-fees": "Fees",
                        "layout-fixed-header": "Fixed Header",
                        "layout-fixed-navigation": "Fixed Navigation",
                        "layout-fixed-ribbon": "Fixed Ribbon",
                        "layout-fixed-footer": "Fixed Footer",
                        "layout-inside": "Inside .container",
                        "layout-rtl-support": "RTL Support",
                        "layout-menu": "Menu on top",
                        "layout-for-colorblind": "For Colorblind",
                        "layout-colorblind-experimental": "experimental",
                        "layout-smartadmin-skins": "SmartAdmin Skins",
                        "layout-smart-default": "Smart Default",
                        "layout-dark-elegance": "Dark Elegance",
                        "layout-ultra-light": "Ultra Light",
                        "layout-google-skin": "Google Skin",
                        "layout-pixelSmash": "PixelSmash",
                        "layout-glass": "Glass",
                        "layout-MaterialDesign": "MaterialDesign",
                        "layout-options": "Layout Options",
                        "layout-clear-localstorage": "Clear Localstorage",
                        "factory-reset": "Factory Reset",
                        "clear-localstorage-text": "Would you like to RESET all your saved widgets and clear LocalStorage?",
                        "localstorage-btn-yes": "YES",
                        "localstorage-btn-no": "NO",
                        "nav-sing-message": "Sign Message",
                        "nav-verify-message": "Verify Message",
                        "sign-message-text": "You can sign messages/agreements with your addresses to prove you can receive bitcoins sent to them. Be careful not to sign anything vague or random, as phishing attacks may try to trick you into signing your identity over to them. Only sign fully-detailed statements you agree to.",
                        "sign-message-signature": "Signature",
                        "message-clear": "Clear All",
                        "verify-message-text": "Enter the receiver's address, message (ensure you copy line breaks, spaces, tabs, etc. exactly) and signature below to verify the message. Be careful not to read more into the signature than what is in the signed message itself, to avoid being tricked by a man-in-the-middle attack. Note that this only proves the signing party receives with the address, it cannot prove sendership of any transaction!",
                        "helpitem-overview-whatstreembitui": "What is Streembit?",
                        "helpitem-overview-opensource": "Open source",
                        "helpitem-overview-systemarchitecture": "System architecture",
                        "helpitem-overview-internet-devices": "Internet of Things devices",
                        "helpitem-settings-config": "Settings, configuration",
                        "helpitem-settings-config-your-streembit": "Configure your Streembit",
                        "helpitem-settings-config-create-account": "Create account",
                        "helpitem-settings-config-backup-account": "Backup account",
                        "helpitem-settings-config-delete-account": "Delete account",
                        "helpitem-settings-config-log-files": "Log files",
                        "helpitem-network": "Streembit network",
                        "helpitem_network_connect_public": "Connect to public network",
                        "helpitem_network_connect_private": "Connect to private network",
                        "helpitem-network-share-keys": "Share your keys",
                        "helpitem-system": "System",
                        "helpitem-system-clear-database": "Clear database",
                        // messages of connection info panel
                        "current-connection-header": "Current Connection Info",
                        "current-connection-account": "Account",
                        "current-connection-transport": "Transport",
                        "current-connection-host": "Host",
                        "current-connection-port": "Port",
                        "current-connection-pubkey": "Public key",
                        // messages for error codes, add an 'errcode_' prefix at the message
                        "errcode_SYSTEM": "System error",
                        "errcode_BADPARAM": "Bad paramater was sent to the procedure",
                        "errcode_INVALID_PAYLOAD": "Invalid payload was sent to the procedure",
                        "errcode_EVENT": "Event handler failed",
                        "errcode_DATABASE": "Database failed",
                        "errcode_HTTP": "HTTP procedure failed",
                        "errcode_HTTP_HANDLEREQUEST": "HTTP handle request failed",
                        "errcode_HTTP_NOWSINFO": "No WS info available at HTTP procedure",
                        "errcode_HTTP_NOWSPEERS": "There are no WS peers available at the HTTP procedure",
                        "errcode_WS": "WebSocket procedure failed",
                        "errcode_WS_ONSEND": "WebSocket onsend handler procedure failed",
                        "errcode_WS_PING": "WebSocket ping procedure failed",
                        "errcode_WS_REGISTER": "WebSocket register client procedure failed",
                        "errcode_WS_DHTPUT": "WebSocket dhtput procedure procedure failed",
                        "errcode_WS_DHTGET": "WebSocket dhtget procedure procedure failed",
                        "errcode_WS_PEERMSG": "WebSocket peer message procedure failed",
                        "errcode_WS_CONTACT_SESSION": "WebSocket session does not exists for contact",
                        "errcode_WS_PEERCOMM": "WebSocket peer communication error",
                        "errcode_UI_CONNECT_TONETWORK": "Error in connecting to Streembit network",
                        "errcode_UI_ON_PEERMSG": "Error in handling message from peer",
                        "errcode_UI_WEBRTC_FILE": "WebRTC file send procedure failed",
                        "errcode_UI_WEBRTC_DATA": "WebRTC data send procedure failed",
                        "errcode_UI_WEBRTC_SCREENSHARE": "WebRTC screen share procedure failed",
                        "errcode_UI_FINDCONTACT": "Finding contact failed",
                        "errcode_UI_ACCOUNTINIT": "Account initialize error",
                        "errcode_UI_ACCOUNTRESTORE": "Restore account error",
                        "errcode_UI_ADDYOURSELFCONTACT": "Can't add yourself as a contact",
                        "errcode_UI_ADDCONTACT": "Add contact error",
                        "errcode_UI_INVALIDCONTACT": "Invalid contact request",
                        "errcode_UI_SIGNATURE_VERIFICATION": "Signature verification failed. Invalid contact offer object",
                        "errcode_UI_INVALID_CONTACT_OFFER": "Invalid contact offer object",
                        "errcode_UI_PUBLIC_KEY_MISMATCH": "Invalid contact offer object. Public key mismatch",
                        "errcode_UI_PARSING_CONTACT_OFFER": "Error in parsing the contact offer object",
                        "errcode_UI_COPYING_NOT_SUPPORTED": "Programmable coping not supported by your environment",
                        "errcode_UI_MAX_ALLOW_FILE_SIZE": "Maximum allowed file size is 64Kb, your file has",
                        "errcode_UI_CREATING_OFF_CONTACT_REQ": "Error in creating offline contact request",
                        "errcode_UI_INITIALIZE_ACCOUNT_BY_CONNECT_STR": "First initialize the account by connecting to the Streembit network",
                        "errcode_UI_CONTACT_ONLASTPING": "contact onLastPing error",
                        "errcode_UI_SETTINGS_INIT": "Settings init error",
                        "errcode_UI_UPDATE_SETTINGS_DB": "Error in updating the settings database. Error",
                        "errcode_UI_EXCEPTION_OCCURED_UPD_SETT_DB": "Exception occured in updating the settings database. Error",
                        "errcode_UI_INVALID_SEED_DATA": "Invalid seed data. The host IP address or domain name and port key are required",
                        "errcode_UI_DELETING_ACCOUNT_FROM_LDB": "Deleting account from local database error",
                        "errcode_UI_SEND_FILE_VM": "Send  file VM onerror",
                        "errcode_UI_ACCEPT-FILE": "The contact refused to accept the file",
                        "errcode_UI_FILE_TRANSFER": "Error in starting file transfer",
                        "errcode_UI_INVALID_SEND_FILE_PARAMS": "Invalid send file parameters",
                        "errcode_UI_IN_SENDING_FILE": "Error in sending the file",
                        "errcode_UI_CREATE_ACCOUNT": "There is no existing user Streembit account in the database. Please create an account to continue",
                        "errcode_UI_ERROR_CREATING_ACCOUNT": "Error in creating the account",
                        "errcode_UI_ERROR_SAVING_ACCOUNT": "Error in saving the account to local database",
                        "errcode_UI_UPDATE_SETTINGS": "Update settings error",
                        "errcode_UI_ERROR_CREATING_ACCOUNT_USER": "Error in creating the account user",
                        "errcode_UI_CHANGE_PWD_INIT-ACCOUNT": "To change the password first you must initialize your account",
                        "errcode_UI_ERROR_CHANGING_PWD": "Error in changing password",
                        "errcode_UI_CONTACT_ONCONTACTWARNING": "contact onContactWarning error",
                        "errcode_UI_CONTACT_ONCONTACTONLINE": "contact onContactOnline error",
                        "errcode_UI_CONTACT_ONCONTACTOFFLINE": "contact onContactOffline error",
                        "errcode_UI_PROCESSING_DELETION_CHATHISTORY": "Error processing deletion of chat history",
                        "errcode_UI_SYNCING_CHAT": "Error syncing chat",
                        "errcode_UI_CONTACT_ONFILERECEIVE": "contact onFileReceive error",
                        "errcode_UI_CONTACT_ERROR": "Contact error",
                        "errcode_UI_CONTACT_ONTEXTMESSAGE": "contact onTextMessage error",
                        "errcode_UI_CONTACT_ITEMACTION": "contact itemAction error",
                        "errcode_UI_CONTACT_ONCONTACTERROR": "contact onContactError error",
                        "errcode_UI_ERROR_SAVING_CHAT_HISTORY": "Error saving chat history",
                        "errcode_UI_ERROR_IN_PINGING_CONTACT": "Error in pinging to contact",
                        "errcode_UI_ESTABLISH_CALL_WITHCONTACT": "Unable to establish call with contact",
                        "errcode_UI_STARTING_VIDEO_CALL": "Error in starting video call",
                        "errcode_UI_SHARING_SCREEN": "Error in sharing the screen",
                        "errcode_UI_NO_REPLY_FROM_CONTACT": "Error in sharing screen, no reply from the contact",
                        "errcode_UI_STARTING_CHAT": "Error in starting chat",
                        "errcode_UI_CHAT_REPLY_FROM_CONTACT": "Error in starting chat: no reply from the contact",
                        "errcode_UI_START_CHAT_ERROR": "Start chat error",
                        "errcode_UI_SEND_FILE_ERROR": "Send file error",
                        "errcode_UI_START_WEBRTC_CALL": "Start WebRTC call error",
                        "errcode_UI_REMOVING_PARTICIPANT": "Error on removing participant, Not found by pkeyhash",
                        "errcode_UI_PROCESSING_ONPERRHANGUP": "Error processing onPerrHangup",
                        "errcode_UI_STARTING_CHAT_NO_WEBRTC_CONN": "Error in starting chat, no WebRTC connection",
                        "errcode_UI_SEND_CHAT_ERROR": "Send chat error",
                        "errcode_UI_INVALID_WEBRTC_DATA_CONN": "invalid WebRTC data connection",
                        "errcode_UI_UNABLE_SEND_DATA": "Unable to send data. No session exists with the contact",
                        "errcode_UI_VERIFYING_GROUPCALL_IDENTITY": "Error verifying groupcall identity",
                        "errcode_UI_PINGING_NEW_GROUPCHAT_ATTENDEE": "Error pinging new groupchat attendee",
                        "errcode_UI_WEBRTC_CONN_DOESNOT_EXISTS": "WebRTC connection does not exists",
                        "errcode_UI_CHAT_VIEW_ERROR": "Chat view error",
                        "errcode_UI_UNABLE_SEND_CHAT_MESSAGE": "Unable to send chat message. No session exists with the contact",
                        "errcode_UI_INVALID_CONTACT_SESSION": "Invalid contact session",
                        "errcode_UI_UNABLE_SYNC_CHAT_HISTORY": "Unable to sync chat history. No session exists with the contact",
                        "errcode_UI_SENDING_CHAT_HISTORY": "Error sending chat history",
                        "errcode_UI_DELETING_CHAT_HISTORY": "Error deleting chat history",
                        "errcode_UI_ADD_IOT_DEVICE": "Add IoT device error",
                        "errcode_UI_DB_CLEAR_ERR": "Database clear error",
                        "errcode_UI_ACCOUNT_ISNOT_INITIALIZE": "the account is not initialized",
                        "errcode_UI_ACCOUNT_DOESNOT_EXISTS": "The account does not exists",
                        "errcode_UI_ACCOUNT_BACKUP_ERR": "Account backup error",
                        "errcode_UI_DB_GET_CONTACTS_ERR": "Database get contacts error",
                        "errcode_UI_NOTVALID_STR_ACCOUNT_BACKUP": "not a valid Streembit account backup",
                        "errcode_UI_INVALID_ACCOUNT_BACKUP_DATA": "Invalid account backup data",
                        "errcode_UI_ACCOUNT_RESTORE_ERR": "Account restore error",
                        "errcode_UI_NOTVALID_STR_CONTACT_BACKUP": "not a valid Streembit contact backup",
                        "errcode_UI_STR_CONTACTS_RESTORE_ERR": "Streembit contacts restore error",
                        "errcode_UI_CONTACTS_RESTORE_ERR": "Contacts restore error",
                        "errcode_UI_CONFIG_FILE_IS_MISSING": "config.json configration file is missing",
                        "errcode_UI_APPCONFIG_SECTION_IS_MISSING": "appconfig section is missing from config.json configration",
                        "errcode_UI_INVALID_CONTACT_ATCONN_CREATE": "invalid contact at connections create",
                        "errcode_UI_INVALID_CALLBACK_ATCONN_CREATE": "invalid callback at connections create",
                        "errcode_UI_CREATE_CHANEL_TIMED_OUT": "Create channel timed out",
                        "errcode_UI_CERTIFICATES_INIT": "Certificates init error",
                        "errcode_UI_VIDEOCALLVM_DISPOSE": "VideoCallVM dispose",
                        "errcode_UI_INVALID_TASK_PROC_ATTR": "invalid task proc attribute",
                        "errcode_UI_INVALID_INFOTASK_OBJECT": "invalid Infotask object",
                        "errcode_UI_ADD_TASK_ERR": "Add task error",
                        "errcode_UI_TASK_WAS_CANCELLED_BYPEER": "The task was cancelled by the peer",
                        "errcode_UI_INVALID_PARAMS_KEYVAL_REQUIRED": "invalid parameters, key and value are required",
                        "errcode_UI_PORT_HOST_REQUIRED": "invalid contact object, port and host are required",
                        "errcode_UI_CONNECTING_STR_TIMEOUT": "Error in connecting Streembit, timed out",
                        "errcode_UI_DB_UPDATE_CONTACT_ERR": "Database update contact error",
                        "errcode_UI_DB_UPDATE_ADD_CONTACT_ERR": "Database update add contact error",
                        "errcode_UI_DELETE_CONTACT_ERR": "Delete contact error",
                        "errcode_UI_VALIDATE_CONTACT_ERR_INVAL_PARAMS": "validate_contact error: invalid parameters",
                        "errcode_UI_CONTACT_FIND_RESAULT_EXCEPTION": "Contact find result exception",
                        "errcode_UI_INIT_CONTACT_ERR": "init_contact error",
                        "errcode_UI_USER_ACCOUNT_ISNOT_INITIALIZED": "the user account is not initialized",
                        "errcode_UI_ERR_INITIALIZING_CONTACTS": "Error in initializing contacts",
                        "errcode_UI_FIRST_INITIALIZE_P2P_NETWORK": "First initialize the account by connecting to the Streembit P2P network",
                        "errcode_UI_THE_ACCOUNT_ISNOT_INITIALIZED": "The account is not initialized. First initialize the account by connecting to the Streembit P2P network",
                        "errcode_UI_FIRST_CONNECT_TOSTR_P2P": "First connect to the Streembit P2P network",
                        "errcode_UI_ERR_DISPLAYING_THE_VIEW": "Error in displaying the view",
                        "errcode_UI_ERR_INITIALIZING_STR_APP": "Error in initializing Streembit application",
                        "errcode_UI_TASK_EXECUTE_ERR": "task execute error",
                        "errcode_UI_INVALID_TASK_PARAMS": "invalid task parameters",
                        "errcode_UI_TASKHANDLER_ERR": "taskHandler error",
                        "errcode_UI_APP_ERR_ADDRESS_SEED_REQ": "Application error: address for a seed is required",
                        "errcode_UI_CREATE_MNEMONIC_ERR": "create_mnemonic error, invalid pkey parameter",
                        "errcode_UI_GETCRYPTPASS_ERR": "getCryptPassword error: callbacks must be a function",
                        "errcode_UI_CREATE_ACCOUNT_INVALID_PARAMS": "create_account invalid parameters",
                        "errcode_UI_MNEMONOC_RESTORE_REQUIRES": "The mnemonic restore requires the value of mnemoic to be set prior calling the create_key procedure",
                        "errcode_UI_INVALID_PARAMS_ACCOUNT_MISSING": "Invalid parameters, the account is missing",
                        "errcode_UI_INVALID_PARAMS_PASS_REQUIRED": "Invalid parameters, passwords is required",
                        "errcode_UI_INVALID_ACCOUNT_NAME": "Invalid account name",
                        "errcode_UI_INVALID_ACCOUNT_SALT_VAL": "Invalid account salt value",
                        "errcode_UI_ACCOUNT_PASS_AREREQUIRED": "Invalid parameters, the account and passwords are required",
                        "errcode_UI_EXISTING_CRYPTO_KEY_INVALID": "the existing crypto key is invalid",
                        "errcode_UI_INVALID_CALLTYPE_RECEIVED": "Invalid call type received from",
                        "errcode_UI_ERR_READING_FILE": "Error in reading the file",
                        "errcode_UI_INVALID_ONREAD_CALLBACK": "invalid onread callback",
                        "errcode_UI_FILE_SEND_ERR_INVALID_FILE": "File send error: invalid file",
                        "errcode_UI_FILE_SEND_ERR_INVALID_FILE_NAME": "File send error: invalid file name",
                        "errcode_UI_FILE_IS_EMPTY_SELECT_FILE": "File is empty, please select a non-empty file",
                        "errcode_UI_MAX_SUPPORTED_FILE_SIZE": "The maximum supported file size of this software version is 100 MB",
                        "errcode_UI_INVALID_FILE_OBJECT_FILETRANS": "Invalid file object at filetrans",
                        "errcode_UI_FAILED_RESEIVE_DATA_FROM_FILEREAD": "Failed to receive data from file read",
                        "errcode_UI_INVALID_FILE": "Invalid file",
                        "errcode_UI_FILE_RECEIVE_ERR": "File receive error",
                        "errcode_UI_UNABLE_ESTABLISH_CONN_WITH_CONTACT": "Unable to establish a connection with this contact",
                        "errcode_UI_ERR_INVITING": "Error on inviting",
                        "errcode_UI_INVALID_SEED_LIST": "invalid seed list",
                        "errcode_WS_POPULATING_PEER_LIST": "Error in populating WS peer list",
                        "errcode_WS_POPULATING_PEER_LIST_FROM_GITREPO": "Error in populating WS peer list from Github repository",
                        "errcode_WS_ONMESSAGE_RECEIVED_ERR": "WebSocket onMessage received error",
                        "errcode_UI_IOT_RESPONDED_AUTHENTICATE_ERR": "IoT Hub responded authenticate error",
                        "errcode_UI_IOTHUBSHANDLER_INITHUB_ERR": "IoTHubsHandler inithub error",
                        "errcode_UI_IOTHUB_INITIALIZE_DEVICES_LIST_ERR": "IoT Hub initialize devices list error",
                        "errcode_UI_IOTHUBSHANDLER_CHECK_CONN_ERR": "IoTHubsHandler check_connections error",
                        "errcode_WS_HUB_SEND_ERR": "WS hub send error",
                        "errcode_UI_IOTHUBSHANDLER_INIT_ERR": "IoTHubsHandler init error",
                        "errcode_WS_ONMESSAGE_RECEIVED_ERR": "WebSocket onMessage received error",
                        "errcode_UI_INVALID_CB_AT_NODE_GET": "invalid callback at node get",
                        "errcode_UI_INVALID_DATA_PARAMS": "invalid data parameter",
                        "errcode_UI_INVALID_CONTACT_OBJECT": "invalid contact object",
                        "errcode_UI_INVALID_CONTACT_TRANSPORT": "invalid contact transport",
                        "errcode_UI_INVALID_CONTACT_PKEYHASH": "invalid contact pkeyhash",
                        "errcode_UI_SETREMOTEDESCRIPTION_ERR": "setRemoteDescription error",
                        "errcode_UI_ERR_START_WEBRTC_CALL": "Error on start WebRTC call with",
                        "errcode_UI_CANT_ADD_PARTICIPANT": "Can not add participant",
                        "errcode_UI_SESSION_KEY_DOESNT_EXIST": "session key does not exist",
                        "errcode_UI_WEBRTC_CONN_INIT_PARAMS": "Invalid WebRTC connection init parameters",
                        "errcode_UI_SETLOCALDESCRIPTION_ERR": "setLocalDescription error",
                        "errcode_UI_CONN_CREATEOFFER_ERR": "connection createOffer error",
                        "errcode_UI_WEBRTC_ADDICECANDIDATE_ERR": "WEBRTC: addIceCandidate error",
                        "errcode_UI_ERR_CREATING_SESSION_DESCRIPTION": "Error creating session description",
                        "errcode_UI_INVALID_FILE_DATA_RECEIVED": "Invalid file data received",
                        "errcode_UI_INVALID_TYPEOF_EVENT_DATA": "Invalid type of event data",
                        "errcode_UI_ONRECEIVESIGNAL_ERR_UNKNOWSIGNALTYPE": "onReceiveSignal error: unknown signal type",
                        "errcode_UI_CLOSE_DATA_CHANNEL_ERR": "Close data channel error",
                        "errcode_UI_FILE_TRANSFER_ERR": "File transfer error",
                        "errcode_UI_ICE_RESOLVER_CONFIG_ISMISSING": "Ice resolver configuration is missing",
                        "errcode_UI_INVALID_PARAMS": "invalid parameters",
                        "errcode_UI_CANNOT_SEND_EMPTY_FILE": "cannot send empty file",
                        "errcode_UI_CONTACT_PARAMS_ISMISSING": "contact parameter is missing",
                        "errcode_UI_ERR_RECEIVING_FILE_READ_DATA": "Error in receiving file read data",
                        "errcode_UI_FILETRANS_INITSEND_ERR": "filetrans.initsend error",
                        "errcode_UI_SEND_FILE_WEBRTC_ERR": "Send file webrtc error",
                        "errcode_UI_INVALID_FILE_RECEIVE_PARAMS": "invalid file receive parameters",
                        "errcode_UI_RECEIVE_FILE_WEBRTC_ERR": "Receive file webrtc error",
                        "errcode_UI_INVALID_CONTACT_WEBRTCDATA_CONSTRUCTOR": "invalid contact at WebRTCData constructor",
                        "errcode_UI_APP_USER_ISNTYET_INITIALIZED": "the application user is not yet initialized",
                        "errcode_UI_INVALID_MESSAGE": "invalid message",
                        "errcode_UI_INVALID_AUD_ELEMENT": "invalid aud element",
                        "errcode_UI_INVALID_SENDER_ELEMENT": "invalid sender element",
                        "errcode_UI_PUBLIC_KEY_EXIST_FORSENDER": "The public key must exists for the sender",
                        "errcode_UI_INVALID_JWT_MESSAGE": "invalid JWT message",
                        "errcode_UI_HANDLESYMMMESSAGE_ERR": "handleSymmMessage error, session does not exist for",
                        "errcode_UI_INVALID_DATA_RECEIVED": "invalid data received",
                        "errcode_UI_INVALID_DATA_COMMAND_RECEIVED": "invalid data command received, 'TXTMSG' is expected",
                        "errcode_UI_UNSUPPORTED_MESSAGE_TYPE": "Unsupported message type",
                        "errcode_UI_HANDLE_MESSAGE_ERR": "Handle message error",
                        "errcode_UI_WEBRTC_RECEIVE_DATA_ERR": "WebRTC receive data error",
                        "errcode_UI_DATA_SEND_ERR": "Data send error",
                        "errcode_UI_ICE_RESOLVER_CONFIG_MISSING_CREATE_CHANNEL": "Ice resolver configuration is missing at create channel",
                        "errcode_UI_CONTACT_PARAMS_MISSING_CREATE_CHANNEL": "Contact parameter is missing at create channel",
                        "errcode_UI_REMOTE_STREAM_INVALID": "the remote stream is invalid",
                        "errcode_UI_ONREMOTESTREAMADDED_ERR": "onRemoteStreamAdded error",
                        "errcode_UI_INVALID_SHARECREEN_MEDIA_STREAM": "Invalid sharescreen media stream",
                        "errcode_UI_SCREENSHARING_WEBBROWSER_NOTSUPPORT": "Screen sharing in web browser is not supported",
                        "errcode_UI_ONCONNECT_CB_PARAMS_MISSING": "onconnect callback parameter is missing",
                        "errcode_UI_ONERR_CB_PARAM_MISSING": "onerror callback parameter is missing",
                        "errcode_UI_TASKID_PARAM_MISSING": "taskid parameter is missing",
                        "errcode_UI_RECEIVE_SCREEN_WEBRTC_ERR": "Receive screen webrtc error",
                        "errcode_UI_SHOW_VIDEO_ERR": "Show video error",
                        "errcode_UI_HIDE_VIDEO_ERR": "Hide video error",
                        "errcode_UI_INVALID_MEDIA_STREAM": "Invalid media stream",
                        "errcode_UI_CALL_CONTACT_ERR": "call_contact error",
                        "errcode_UI_MEDIA_CALL_INITIALIZE_ERR": "Media call initialization error",
                        "errcode_UI_ONREADYFORSTREAM_ERR": "onReadyForStream error",
                        "errcode_UI_ONSTREAMREMOVED_ERR": "onStreamRemoved error",
                        "errcode_UI_ONSTREAMCREATED_ERR": "onStreamCreated error",
                        "errcode_UI_GET_USER_MEDIA_ERR": "Get user media error",
                        "errcode_WS_ERR": "Web socket error",
                        "errcode_UI_ONPEERERR_ERR": "onPeerError error",
                        "errcode_UI_ACCEPT_KEY_UNABLETO_COMPLETE": "Accept key unable to complete, session does not exist for",
                        "errcode_UI_HANDLEACCEPTKEY_ERR": "handleAcceptKey error",
                        "errcode_UI_INVALID_PUBLICKEY_FORCONTACT": "invalid public key for contact",
                        "errcode_UI_INVAL_MSG_DATA_FORKEYCONT": "invalid message data for key exchange contact",
                        "errcode_UI_INVAL_SESSION_SYMMKEY_FORCONT": "invalid session symmetric key for contact",
                        "errcode_UI_PEER_SEND_MSGERR": "Peer send message error",
                        "errcode_UI_HANDLE_KEY_EXCHANGE_ERR": "Handle key exchange error",
                        "errcode_UI_HANDLE_PING_PEER_SEND_ERR": "Handle ping peer send error",
                        "errcode_UI_HANDLE_PING_ERR": "Handle ping error",
                        "errcode_UI_HANDLEPING_ERR": "handlePing error",
                        "errcode_UI_HANDLEPINGREPLY_ERR": "handlePingReply error",
                        "errcode_UI_HANDLEHANGUPCALL_ERR": "handleHangupCall error, session does not exist for",
                        "errcode_UI_HANDLECALLREPLY_ERR": "handleCallReply error",
                        "errcode_UI_SHARE_SCREEN_OFFER_ERR": "Share screen offer error, session does not exist for",

                        // generic error in case there is no error code
                        "errcode_PROCERROR": "Procedure failed",
                        "errcode_MAX_ERROR_CODE": "0xFFFF",
                        "ERROR": "Application error",
                        // miscellaneous
                        "error-word": "Error",
                        "reason-word": "Reason",
                        "info-word": "Info",


                    }
                },
                de: {
                    translation: {
                        "ERROR": "Anwendungsfehler",
                        "appname-title": "Streembit",
                        "appname-sub-title": "German Decentralized, peer-to-peer, secure communication system for humans and machines",
                        "appload-streembit": "German Load Streembit",
                        "appload-locals": "German Load localization resources",
                        "appload-database": "German Load database",
                        "appload-logger": "German Load application logger",
                        "appload-kademlia": "German Load Kademlia DHT",
                        "lbl-initui-connect": "Verbunden",
                        "lbl-initui-newaccount": "Neues Konto",
                        "lbl-initui-initexisting": "Initialisieren Bestehenden Konto",
                        "lbl-initui-restore": "Wiederherstellung Konto",

                        // errors
                        // TODO

                        // miscellaneous
                        "error-word": "Fehler",
                        "reason-word": "Grund"
                    }
                }
            }
        },
        (err, t) => {
            if (!err) {
                console.log('Local resources loaded');
                resolve();
            }
            else {
                reject(err);
            }
        });
    }); 
}


