/*

This file is part of Streembit application. 
Streembit is an open source communication application. 

Streembit is a free software: you can redistribute it and/or modify it under the terms of the GNU General Public License 
as published by the Free Software Foundation, either version 3.0 of the License, or (at your option) any later version.

Streembit is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Streembit software.  
If not, see http://www.gnu.org/licenses/.
 
-------------------------------------------------------------------------------------------------------------------------
Author: Streembit development team
Copyright (C) Streembit 2017
-------------------------------------------------------------------------------------------------------------------------

*/

import i18next from 'i18next';

// TODO get this from a resource files based on the language
var ErrorCodes = {
    "en": {

    }
};

export default function () {
    return new Promise((resolve, reject) => {
        i18next.init({
            lng: 'en',
            resources: {
                en: {
                    translation: {                        
                        "appname-title": "Streembit",
                        "appname-sub-title": "Decentralized, peer-to-peer communication system for humans and machines",
                        "appload-streembit": "Load Streembit",
                        "appload-application": "Load application",
                        "appload-components": "Loading UI components",
                        "appload-datadir": "Create application data directory",
                        "appload-databind": "Create data binders",
                        "appload-database": "Load database",
                        "appload-logger": "Creating application logger",
                        "appload-settings": "Load settings from local database",
                        "appload-accounts": "Load accounts from local database",
                        "appload-apputils": "Create application utility handler",
                        "appload-contacts": "Load contacts from local database",
                        "appload-contact-handler": "Initialize contacts handler",
                        "appload-events": "Create event handlers",
                        "appload-kademlia": "Load Kademlia DHT",
                        "appload-streembitconn": "Connecting to the Streembit P2P network",
                        "appload-complete": "Application resource loading has been completed",
                        "lbl-initui-connect": "Connect",
                        "lbl-initui-newaccount": "New Account",
                        "lbl-initui-initexisting": "Initialize Existing Account",
                        "lbl-initui-restore": "Restore Account",
                        "lbl-createaccount-create": "Create new Streembit account",
                        "lbl-connectto-public-net": "Initialize Streembit account",
                        "lbl-connect": "Connect",
                        "lbl-submit": "Submit",
                        "lbl-streembitacc": "Streembit account",
                        "lbl-saved-accounts": "Saved accounts",
                        "lbl-privkeypassword": "Private key password",
                        "lbl-confirmpassword": "Confirm private key password",
                        "lbl-changepwd-title": "Change your Streembit password",
                        "lbl-changepwd-change": "Change password",
                        "errmsg-createaccount-accountname": "The account name must be between 6-20 characters and it can only contain alphanumeric characters (letters a-z, A-Z and numbers 0-9)",
                        "errmsg-createaccount-exists": "The account already exists in your account list.",
                        "errmsg-createaccount-pwdrequired": "Password is required",
                        "errmsg-createaccount-pwdlength": "The password must be at least 8 characters",
                        "errmsg-createaccount-nospaceallowed": "The password must not contain empty space",
                        "errmsg-createaccount-lowercaseneed": "The password must contain at least one lower case letter",
                        "errmsg-createaccount-uppercaseneed": "The password must contain at least one upper case letter",
                        "errmsg-createaccount-digitneed": "The password must contain at least one digit",
                        "errmsg-createaccount-specialcharneed": "The password must contain at least one special character",
                        "errmsg-createaccount-pwdconfirm": "Password confirm input value is required",
                        "errmsg-createaccount-pwdconfirmmatch": "The password and its confirm are not the same",
                        "errmsg-connectaccount-select": "Select an account from the saved account list",
                        "appmsg-nopeer-wsuseprompt": "Unable to connect via the TCP peer connection. Most likely your firewall, port forwarding or UPnP configuration is blocking the communication via TCP.\nWould you like to use WebSocket connection? Your signalling and contact discovery will be performed by a WebSocket server, but your video, audio, text communication and file sending will still be fully encrypted and peer-to-peer.",
                        "appmsg-askwspublish": "Would you like to publish data to Streembit WebSocket hubs? Using WebSocket enables communication with users who are unable to etablish a TCP connection. Using WS signalling your video, audio, text communication and file sending will still be fully encrypted and peer-to-peer.",
                        "errmsg-wallet-send-recipient": "Recipient is a string 30-40 chars long. no blanks, no special chars",
                        "errmsg-wallet-send-amount": "Amount is not empty, can be a floating",
                        "errmsg-wallet-send-fees": "Fees is not empty, can be a floating",
                        "errmsg-wallet-receive-message": "Message contains chars that we do not accept",
                        "errmsg-wallet-receive-label": "Label contain unacceptable characters",
                        "errmsg-transport-send": "There is an error processing your request. Please, try again later",
                        "lbl-restore-account": "Restore Account",
                        "lbl-restore-backup": "Restore from Backup",
                        "ttlbtn-restore-mnemonic": "Restore from Mnemonic",
                        "btn-hide-restore-mnemonic": "Hide mnemonic field",
                        "sbm-restore-mnemonic": "Restore",
                        "lbl-mnemonic": "Mnemonic",
                        "lbl-restore-mnemonic": "Restore private key from Mnemonic",
                        "errmsg-remnemonic-invalid": "Invalid mnemonic",
                        "errmsg-remnemonic-validation-failed": "Mnemonic validation failed. Check spelling and wording",
                        // view titles
                        "view-title-dashboard": "Dashboard",
                        "view-title-help": "Help",
                        "view-title-settings": "Settings",
                        "view-title-netinfo": "Account, network info",
                        "view-title-logs": "Logs",
                        "view-title-certificates": "X.509 certificates",
                        "view-title-utilcerts": "Utility certificates",
                        "view-title-commsecurity": "Communication security",
                        "view-title-addiothub": "Add IoT Hub",
                        "view-title-devices": "My Devices",
                        "view-title-wallet": "Wallet",
                        "view-title-balance": "Balance",
                        "view-title-contact": "Contact details",
                        "view-title-contact-chat": "Text chat",

                        "wal-dinamic-fees": "Use dynamic fees",
                        "wal-fees-manually": "Edit fees manually",
                        "wal-propose-replace": "Propose Replace-By-Fee:",
                        "wal-fee-unit": "Fee Unit:",
                        "wal-change-address": "Use change addresses",
                        "wal-multiple-change-address": "Use multiple change addresses",
                        "wal-coin-section": "Coin Section",
                        "wal-confirmed-coins": "Spend only confirmed coins",
                        "wal-language" : "Language:",
                        "wal-decimal-point": "Zeros after decimal point:",
                        "wal-base-unit": "Base unit",
                        "wal-currency": "Fiat currency",
                        "wal-history-rates": "Show history rates",
                        "wal-fiatBalance-address": "Show fiat balance for addresses",
                        "wal-open-alias": "Open Alias:",
                        "wal-ssl-certificate": "SSL certificate:",
                        "col-balance": "Balance",
                        "col-recent-transactions": "Recent transactions",
                        "col-appearance" : "Appearance",
                        "col-fiat": "Fiat",
                        "col-identity": "Identity",
                        "tab-payTo": "Pay To:",
                        "tab-label": "Label:",
                        "tab-amount": "Amount:",
                        "tab-address": "Address",
                        "tab-transaction-fees": "Transaction Fees",
                        "tab-SBCoin": "SBCoin/kB",
                        "tab-request-replace-be-fee": "Request replace be Fee",
                        "btn-clear": "Clear",
                        "btn-copy-uri": "Copy URI",
                        "btn-copy-address": "Copy Address",
                        "btn-save-image": "Save Image",
                        "btn-close": "Close",
                        "tab-message": "Message",
                        "tab-request-payment-history": "Requested Payment History",
                        "tb-header-text-date": "Date",
                        "tb-header-text-address": "Address",
                        "tb-header-test-label": "Label",
                        "tb-header-amount-req": "Amount",
                        "tb-header-amount-tranc": "Amount Transacted (SBCoin)",
                        "tb-header-type": "Type",
                        "tb-header-balance": "Balance",
                        "nav-overview": "Overview",
                        "nav-send-money": "Send Money",
                        "nav-receive-money": "Receive Money",
                        "nav-transactions": "Transactions",
                        "coin-name": "SBCoin",
                        "mainMenuFile": "File",
                        "delete": "Delete",
                        "backup": "Backup",
                        "menu-title-security": "Security",
                        "menu-title-actions": "Actions",
                        "menu-item-restore-wallet": "Restore wallet",
                        "menu-item-backup-wallet": "Backup wallet",
                        "menu-item-delete-wallet": "Delete wallet",
                        "menu-item-password": "Password",
                        "menu-item-seed": "Seed",
                        "menu-item-private-keys": "Private keys",
                        "menu-item-history": "Export history",
                        "menu-title-settings": "Settings",
                        "menu-item-contract": "Create smart contract",
                        "menu-item-preferences": "Preferences",
                        "menu-item-network": "Network",
                        "menu-item-sign-message": "Sign message",
                        "menu-item-verify-message": "Verify message",
                        "menu-item-encrypt": "Encrypt",
                        "menu-item-load-transaction": "Load transaction",
                        "menu-item-from-text": "from text",
                        "menu-item-from-blockchain": "from blockchain",
                        "menu-item-qr-code": "from QR code",
                        "menu-item-documentation": "Documentation",
                        "password-item-title": "Your wallet is password protected and encrypted.Use this dialog to change the password.",
                        "text": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
                        "delete-text": "You are about to delete a and all of its contents.",
                        "deleteOp": "This operation is permanent and cannot be undone.",
                        "passworddialog": "Your wallet is password protected and encrypted.Use this dialog to change the password.",
                        "currentpass": "Current Password:",
                        "newpassword": "New Password:",
                        "confirmpass": "Confirm Password:",
                        "enterpass" : "Please enter your password",
                        "next-button": "Next",
                        "col-fees": "Fees",
                        "layout-fixed-header": "Fixed Header",
                        "layout-fixed-navigation": "Fixed Navigation",
                        "layout-fixed-ribbon": "Fixed Ribbon",
                        "layout-fixed-footer": "Fixed Footer",
                        "layout-inside": "Inside .container",
                        "layout-rtl-support": "RTL Support",
                        "layout-menu": "Menu on top",
                        "layout-for-colorblind": "For Colorblind",
                        "layout-colorblind-experimental": "experimental",
                        "layout-smartadmin-skins": "SmartAdmin Skins",
                        "layout-smart-default": "Smart Default",
                        "layout-dark-elegance": "Dark Elegance",
                        "layout-ultra-light": "Ultra Light",
                        "layout-google-skin": "Google Skin",
                        "layout-pixelSmash": "PixelSmash",
                        "layout-glass": "Glass",
                        "layout-MaterialDesign": "MaterialDesign",
                        "layout-options": "Layout Options",
                        "layout-clear-localstorage": "Clear Localstorage",
                        "factory-reset": "Factory Reset",
                        "clear-localstorage-text": "Would you like to RESET all your saved widgets and clear LocalStorage?",
                        "localstorage-btn-yes": "YES",
                        "localstorage-btn-no": "NO",
                        "nav-sing-message": "Sign Message",
                        "nav-verify-message": "Verify Message",
                        "sign-message-text": "You can sign messages/agreements with your addresses to prove you can receive bitcoins sent to them. Be careful not to sign anything vague or random, as phishing attacks may try to trick you into signing your identity over to them. Only sign fully-detailed statements you agree to.",
                        "sign-message-signature": "Signature",
                        "message-clear": "Clear All",
                        "verify-message-text": "Enter the receiver's address, message (ensure you copy line breaks, spaces, tabs, etc. exactly) and signature below to verify the message. Be careful not to read more into the signature than what is in the signed message itself, to avoid being tricked by a man-in-the-middle attack. Note that this only proves the signing party receives with the address, it cannot prove sendership of any transaction!",
                        "helpitem-overview-whatstreembitui": "What is Streembit?",
                        "helpitem-overview-opensource": "Open source",
                        "helpitem-what-streembitui-text1": "Streembit is a decentralized, peer to peer (P2P) real time communication system for humans and machines. The application aims to implement a system that securely manages humans to machine and machine to machine (M2M) communication without using a central server or client-server infrastructure. The actors of the system are nodes on a peer-to-peer network. Hardware services are manifested in smart contracts that are accessible via messages and transactions. The system uses a Kademlia distributed hash table (DHT) discover human and machine nodes on the network. The system ensures data integrity using public-private key cryptography. Messages are signed with the contact’s private key on the client side using ECDSA cryptography. The data is encrypted using ECDH key exchange to exchange the cryptography keys between the contacts and AES symmetric encryption. The video and audio chat feature utilizes the WebRTC the protocol that allows a fully encrypted video and audio communication in a true P2P manner, without routing the conversation through of any central servers.",
                        "helpitem-what-streembitui-text2": "Streembit aims to comply with open security and communication standards. The compliance is verifiable via peer review of the Streembit open source system. Streembit is built on FIPS, IETF and W3C security; data and communication standards such as JWT, JWS, WebRTC, as well as the latest planned and actual standards from W3C Web of Things initiative. The system uses recommended curves for the ECDSA and ECDH elliptic curve cryptography functions.",
                        "helpitem-what-streembitui-text3": "Decentralisation addresses several major system and business requirements. Decentralised systems are scalable; in fact they become more stable if there are more active users. This means that no expensive cluster servers are needed to run a decentralised system. The peers make up the system with their home and office computers, tablets, and mobile devices.",
                        "helpitem-what-streembitui-text4": "Decentralised systems are the composite of their peers, and are always available as long as at least two peers are connected. On the other hand, centralised systems require expensive load balancers, and even more costly data centers across geographical regions to provide high availability. A decentralised P2P system makes centralised high-cost server infrastructures obsolete.",
                        "helpitem-what-streembitui-text5": "Human right activists, dissidents, and citizens who stand up against totalitarian states and undemocratic policies also need a secure communication tool. Oppressive regimes are even cracking down on critics beyond their own borders. A decentralised peer to peer system, in which the communication is fully encrypted between the users, preserves privacy without using a central server, and keeps the data safe from oppressive regimes.",
                        "helpitem-overview-systemarchitecture": "System architecture",
                        "helpitem-overview-opensource-text": "The system is free, fully open source and released under the Apache 2.0 license. The source code is available at https://github.com/Streembit. Users can download the source and build the application from directly the source code. We encourage peer review by security experts and software developers to verify there are no security backdoors exist in the system and the application complies with security and communication standards (FIPS, JWT, JWS, JWE, etc).",
                        "helpitem-overview-systemarchitecture-text1": "The Streembit system forms a decentralized peer to peer network to manage connections between machines and machines or humans and machines.  The participants in the network are the peer nodes. The peer to peer network is scalable and an unlimited number of nodes can participate in the network.",
                        "helpitem-overview-systemarchitecture-text2": "The system performs public private key infrastructure based authentication and access control functions to securely connect peer nodes. The application generates at least one private/public key pair on each peer node including on the Internet-of-Things devices. The actors of the system publish their public keys to the peer to peer network via a Kademlia distributed hash table (DHT). Each peer node knows the public key of the other connected peer nodes.  The system identifies peer nodes in the peer to peer network by their public key. To ensure data integrity the nodes sign the messages with their private key. The nodes sign all messages -  there are no unsigned messages circulated in the system. (The requirement for signing the messages also help to mitigate the risks of Sybil attacks and DDoS attacks).",
                        "helpitem-overview-systemarchitecture-text3": "Streembit supports two types of network implementations:",
                        "helpitem-overview-systemarchitecture-public-network": "Public network. Anyone can connect, there is no security gate enabled in the public network. The main Streembit network is public.",
                        "helpitem-overview-systemarchitecture-private-network": "Private network, which implements a security gate to provide only a set of preconfigured contacts with access. A private Streembit network is isolated from the public Streembit network. Only certain peer nodes are allowed to connect to the network. The access control is governed by built in authentication functions. Typically, IoT devices within a building, teams, communities or businesses would run a private Streembit network to establish an even more secure communication mechanism than the public Streembit network. A private Streembit network is functioning as a firewall: only preconfigured contacts allowed to connect. The collection of the preconfigured contacts is maintained in a lookup list. The connection of devices and users which are not in the preconfigured list is refused by the private network.",
                        "helpitem-overview-security-text1": "The cornerstone of Streembit security is elliptic curve public/private key cryptography infrastructure (PPKI). PPKI allows the implementation of robust security. We use PPKI to identify the entities of the system (based on their public key and PPKI signature), perform authentication, and ensure data integrity (using cryptography signatures). Using the public/private key cryptography infrastructure paves the way for the deployment of a robust, secure authentication and access control scheme. The parties are identified by their public key. The authenticity of messages and the identities of the actors are then verified using PPKI cryptography routines. Using a PPKI infrastructure based security scheme greatly simplifies the authentication, access control, and identity management aspects of Internet-of-Things security.",
                        "helpitem_overview_security-text2": "The elliptic curve cryptography (ECC) scheme is particularly suitable for IoT devices. The small footprint of ECC allows security modules to be implemented on embedded devices. ECDH is a trusted and proven key agreement protocol. Using the ECDSA digital signature algorithm ensures data integrity.",
                        "helpitem_overview_security-text3": "The system performs public/private key infrastructure based authentication and access control functions to securely connect machines to machines or machines to humans. The Streembit security module of the IoT device must generate at least one public/private key pair for each connected IoT device. Human users generate their ECC public/private key pair when they create their account. The actors of the system publish their public keys to the network, where each entity knows the public key of the other connected human or machine. The system identifies each of the entities by their ECC public key.",
                        "helpitem_overview_security-text4": "The collision resistant SHA-256 hash function is used to create a hash of data which can be signed using the private key to guarantee data integrity, as well as provide information about the originator of the data. To ensure data integrity the messages, control commands, event data, requests, and responses are signed with the ECC private key; the signature can be verified using ECDSA. To ensure integrity of data, each entity must sign all messages with their private key. The messages in the Streembit network are based on the following standards: JSON Web Token (JWT), JSON Web Encryption (JWE), and JSON Web Signature (JWS).",
                        "helpitem_overview_security-text5": "Streembit security implementation and design summary",
                        "helpitem_overview_security-text6": "Human users and Internet of Things devices use public/private key (PPK) infrastructure and PPK cryptography functions to secure messages",
                        "helpitem_overview_security-text7": "Each actor of the system must generate a public/private key pair. (Typically keys are generated prior to configuring the device and will be burned into the devices’ firmware).",
                        "helpitem_overview_security-text8": "The device or user publishes the public key to other users of the system.",
                        "helpitem_overview_security-text9": "The data integrity and authenticity of the messages is guaranteed with PPK signatures.",
                        "helpitem_overview_security-text10": "Each session between users is secured with strong symmetric cryptography keys.",
                        "helpitem-overview-security-text11": "All messages between users are secured with 128-bit and 256-bit AES symmetric encryption/decryption.",
                        "helpitem_overview_security-text12": "The system uses elliptic curve Diffie Hellman (ECDH) key exchange algorithms to facilitate the exchange of session keys.",
                        "helpitem_overview_security-text13": "Protecting the ECC public/private key pair",
                        "helpitem_overview_security-text14": "The ultimate issue of all applications, systems, and devices that protect data with cryptography is the security of the symmetric key of the encryption or the private key of the public/private key pair. Similarly to the iPhone and PGP, which both use passcode to protect their keys, Streembit requires users have a passcode to protect their PPKI private key. The Streembit passcode that protects the user’s PPK key pair is relatively complex.",
                        "helpitem_overview_security-text15": "To protect real time communication, Streembit uses a randomly generated 256-bit AES session key and exchanged between peers with a randomly generated ECDH key pair. This means that real time communication, which is the main functionality of Streembit, is secure even from the brute force attacks of NSA super computers and large zombie computer clusters of cyber criminals.",
                        "helpitem_overview_security-text16": "Mitigate the risk of Sybil attacks",
                        "helpitem_overview_security-text17": "A known issue with regards to peer-to-peer (P2P) networks and their practical limitation is that they are frequently subject to Sybil attacks. This means that malicious parties can compromise the network by generating and controlling large numbers of shadow identities. A malicious node may present multiple fake identities to a peer-to-peer network in order to appear and function as several distinct nodes.",
                        "helpitem_overview_security-text18": "A Sybil attack is most effective on anonymous and reputation systems where if the malicious nodes outnumber the honest nodes the outcome of the application could be compromised. For example, on a file sharing network a successful horizontal Sybil attack allows the attacker to sniff most of the control messages, hijack the system, and deliver bogus content. Contrarily, Streembit facilitates communication between contacts that you know, such as your family members, teammates, and business partners. You are also aware of the location and identity of your Internet of Things device(s) you control via Streembit, lessening the likelihood of a Sybil attack. Malicious nodes, regardless of their weight and presence on the network, are unable to change the public keys of your contacts (as the public key is based on the cryptographically secured PPK infrastructure).",
                        "helpitem_overview_security-text19": "Additionally, Streembit introduces another layer of security, private networks. Using private networks, the public keys of the contacts are loaded to the seed nodes manually; mitigating further the risk of a Sybil attack as well as a Man-in-the-middle attack (MITM). A Sybil attack, which generally speaking is a serious security issue for P2P networks such as file sharing applications, is much less of a problem for the Streembit P2P system.",
                        "helpitem_overview_security-text20": "How secure the cryptography of Streembit?",
                        "helpitem_overview_security-text21": "Both 128-bit and 256-bit AES symmetric encryption, the cryptography schemes of the messages in the Streembit network, are safe from any brute force attacks. The following UML diagram describes the key exchange using ECDH and securing the message with 256-bit AES symmetric key between 'User A' and 'User B'.",
                        "helpitem-overview-internet-devices": "Internet of Things devices",
                        "helpitem-overview-internet-devices-text1": "Streembit is a unified communication platform for both human users and Internet of Things devices.",
                        "helpitem-overview-internet-devices-text2": "Streembit manages device discovery as well as authentication, access control and provisioning of devices without using a centralized authority server. The system facilitates device discovery and device control in a peer to peer manner. For many IoT use cases a decentralized, P2P network topology is the most secure, robust, scalable and reliable method of operation. Instead of using expensive corporate owned third party cloud systems, Streembit manages Internet of Things devices without the need of proprietary centralized cloud platforms. Centralized, corporate owned cloud is certainly an easier way to build out IoT platforms. However, the owners and authorities in these topologies all have an influence upon the network and can be exploited. They can ban devices, spy on devices and compromise data integrity of devices. In fact, government can order them to do any or all of these. In the near future, the doors of your garage and home, air conditioning units and your home security system will be fully internet connected. You will be able to control your home automation system from your mobile phone. It is essential that only you can control your IoT devices. Streembit excludes third party service and cloud providers from the ecosystem to give full control to the end users over the devices.",
                        "helpitem-overview-internet-devices-text3": "The primary premise of this system is that all aspects of the IoT device operation must consist of decentralized P2P communication between the device and human user. For example, in the case of a building’s door device: a secure and decentralized P2P system can manage the door (including device configuration, upgrades and provisioning). There is no need to involve a centralized server nor a cloud based solution in order to implement a secure and fully operation Internet of Things system.",
                        "helpitem-overview-internet-devices-text4": "Internet of Things device discovery on Streembit",
                        "helpitem-overview-internet-devices-text5": "Streembit allows IoT application providers and context producers to register their IoT Objects on the decentralised Streembit network, and in turn allow context consumers to discover them in a secure and peer to peer manner. ",
                        "helpitem-overview-internet-devices-text6": "Control Internet of Things devices via Streembit",
                        "helpitem-overview-internet-devices-text7": "The Internet of Things devices and human users communicate with each other directly in a peer to peer manner",
                        "helpitem-overview-internet-devices-text8": "The data is end to end encrypted between the human user and IoT device. The encryption key is shared only between the user and device – never with any third parties.",
                        "helpitem-overview-internet-devices-text9": "The device exposes functionalities via the Streembit network and user interface using W3C WoT standards",
                        "helpitem-overview-internet-devices-text10": "The user interacts with the device via the Streembit P2P layer and UI. For example, opening a door, turning ON a light, controlling motor speed, getting temperature data, viewing CCTV pictures etc. all peer to peer, without a centralised solution and via the Streembit user interface.",
                        "helpitem-overview-internet-devices-text11": "Upgrade and manage Internet of Things devices via Streembit",
                        "helpitem-overview-internet-devices-text12": "Hardware and software providers upgrade Internet of Things devices on the always up and running Streembit network.",
                        "helpitem-overview-internet-devices-text13": "Internet of Things device manufacturers and software designers publishes firmware and software updates via the Streembit network.",
                        "helpitem-overview-internet-devices-text14": "Internet of Things devices run the Streembit system and ensure the origin and data integrity of the updates by verifying the public key of the publisher.",
                        "helpitem-overview-internet-devices-text15": "Standards",
                        "helpitem-overview-internet-devices-text16": "The Streembit Internet of Things system is based on the latest W3C Web of Things standards. The system incorporates the latest modules from the W3C web-of-things-framework. The devices are defined with JSON-LD and the security uses FIPS standards for cryptography and JWT, JWS and JWE standards to secure data.",
                        "helpitem-overview-internet-devices-text17": "To integrate devices with Streembit please refer to the IoT section of the Streembit Github repository.",
                        "helpitem-settings-config": "Settings, configuration",
                        "helpitem-settings-text1": "Streembit settings",
                        "helpitem-settings-text2": "Click on the Tools/Settings menu item to open the Settings screen.",
                        "helpitem-settings-text3": "Network tab",
                        "helpitem-settings-text4": "TCP port:",
                        "helpitem-settings-text5": "Use this TCP port to communicate on the Streembit network. Port forwarding or the UPNP settings of your router must grant access to this port in order to send and receive data. If the transport is WebSocket (WS) then this settings is not used by the application.",
                        "helpitem-settings-text6": "WebSocket port:",
                        "helpitem-settings-text7": "If the TCP port is not available then the connect to the WebSocket listener must listen on this port.",
                        "helpitem-settings-text8": "Transport:",
                        "helpitem-settings-text9": "Transport protocol. The default is TCP. Select the WebSocket transport if the incoming TCP traffic is blocked by your router or firewall. If the WebSocket transport then make sure the WebSocket listener seed node is operational.",
                        "helpitem-settings-text10": "Use WebSocket fallback:",
                        "helpitem-settings-text11": "Many firewalls and home network routers block incoming TCP communication and this is a fallback solution for users who are unable to use the TCP protocol. By enabling this configuration option the system will try to communicate on the WebSocket protocol when the generic TCP communication is blocked. Please note, WebSocket listeners run by community peers and the availability of WebSocket listeners is limited on the network. Try to run your own seed to support the network and Streembit community, and ensure the WebSocket listeners is available! Also, make sure the WebSocket listener is enabled in the seed nodes if you run a private Streembit network!",
                        "helpitem-settings-text12": "Seeds tab",
                        "helpitem-settings-text13": "List of seed nodes:",
                        "helpitem-settings-text14": "The seed nodes assist in user and device discovery, and stores the users’ public key data in their distributed hash table (DHT) storage. Also, you can define here your seed nodes if you run a private Streembit network.",
                        "helpitem-settings-text15": "Ice resolvers tab",
                        "helpitem-settings-text16": "Complete decentralization is not possible in Internet communication. All decentralized systems like Bitcoin or Telehash must use some internet services for certain tasks. For instance, decentralized systems use DNS servers and services to resolve domain names. WebRTC video and audio chats clients use ICE servers to get information about their own IP address.",
                        "helpitem-settings-text17": "Private network tab",
                        "helpitem-settings-text18": "Seed account, Seed port, Seed IP/domain name:",
                        "helpitem-settings-text19": "If the Seed account, Seed port and IP/domain name are defined then the software operates in private network mode. Please note, the seed node must be configured to run as a private network node as well. Remove these configuration settings if you want to connect to the public Streembit network.",
                        "helpitem-settings-text20": "System tab",
                        "helpitem-settings-text21": "Log level:",
                        "helpitem-settings-text22": "Defines the log level. Debug: most detailed logging. Info: only important system events logged. Error: only application errors logged.",
                        "helpitem-settings-text23": "Developer mode:",
                        "helpitem-settings-text24": "Software developers should select this option to resolve directories and develop the software from IDE such as Visual Studio.",
                        "helpitem-settings-config-your-streembit": "Configure your Streembit",
                        "helpitem-settings-config-text1": "If you want to use the Streembit network from your desktop computer, tablet or mobile device and communicate with other peers without using a central server you must allow inbound connections.",
                        "helpitem-settings-config-text2": "Home connections are usually filtered by a router or modem. Streembit will request your router automatically configure itself to allow inbound connections to port 8905. Unfortunately, many routers don’t allow automatic configuration, so you must manually configure your router. You may also need to configure your firewall to allow inbound connections to port 8905. Please see the following subsections for details.",
                        "helpitem-settings-config-text3": "Enabling Connections",
                        "helpitem-settings-config-text4": "If the Streembit application can’t automatically configure your router to open port 8905, you will need to manually configure your router. We’ve tried to make the following instructions generic enough to cover most router models; if you need specific help with your router, please ask for help on a tech support site such as SuperUser.",
                        "helpitem-settings-config-text5": "Enabling inbound connections typically requires two steps, plus an extra third step for firewall users:",
                        "helpitem-settings-config-text6": "Giving your computer a static (unchanging) internal IP address by configuring the Dynamic Host Configuration Protocol (DHCP) on your router.",
                        "helpitem-settings-config-text7": "Forwarding inbound connections from the Internet through your router to your computer where Streembit can process them.",
                        "helpitem-settings-config-text8": "Configuring your firewall to allow inbound connections. This step mainly applies to Windows users, as Mac OS X and most Linuxes do not enable a firewall by default.",
                        "helpitem-settings-config-text9": "Please refer to your router configuration document for port forwarding information.",
                        "helpitem-settings-config-create-account": "Create account",
                        "helpitem-settings-config-create-account-text1": "Human users and Internet of Things devices are identified by their account name on the Streembit network.",
                        "helpitem-settings-config-create-account-text2": "Click on the Streembit/New account menu item or click on the New Account button from the start screen.",
                        "helpitem-settings-config-create-account-text3": "Enter the account name. You will receive an error message if the account exists on the network. The account name must be between 6-20 characters and it can only contain alphanumeric characters (letters a-z, A-Z and numbers 0-9)",
                        "helpitem-settings-config-create-account-text4": "Enter the password key pair encryption password. Based on the password, the system generates a 256-bit AES key using PBKDF2 with a randomly generated 160-bit salt. The system protects the ECC public key pair with the 256-bit AES key. The password must be at least 8 characters, must not contain empty space, must contain at least one letter, one digit and one special character.",
                        "helpitem-settings-config-backup-account": "Backup account",
                        "helpitem-settings-config-backup-account-text1": "You can perform an account backup to save a local copy of your Streembit account data. The Streembit account can be restored from a backup using the “Restore account” function.",
                        "helpitem-settings-config-backup-account-text2": "In order to backup the account the account must be initialized. Click on the Streembit/Backup account menu item to start backup your account.",
                        "helpitem-settings-config-backup-account-text3": "Your account backup data is never saved on a central server by the Streembit application and the account backup file is saved to your Download directory.",
                        "helpitem-settings-config-backup-account-text4": "What is saved in the Backup file?",
                        "helpitem-settings-config-backup-account-text5": "The backup file contains your encrypted Streembit ECC public/private key pair. The backup data is base64 encoded. It starts with “---BEGIN Streembit KEY---“, and the file ends with “---END Streembit KEY---“",
                        "helpitem-settings-config-restore-account-text1": "Restore account from backup file",
                        "helpitem-settings-config-restore-account-text2": "Why restore your account data?",
                        "helpitem-settings-config-restore-account-text3": "Your contacts identify your account and validate your identity using your PPK public key. The public/private key pair is created using a random entropy - once it is created then it cannot be changed. The public/private key pair isn’t deterministic and in order to communicate with your contacts, you must use the same public key which was published to the Streembit network and known to your contacts. The published public key can be restored from an account backup file.",
                        "helpitem-settings-config-restore-account-text4": "You can restore your Streembit account data on any computer from a backup file.",
                        "helpitem-settings-config-restore-account-text5": "Click on the Streembit/Restore account menu item or the Restore account to start restoring the account from a backup file.",
                        "helpitem-settings-config-delete-account": "Delete account",
                        "helpitem-settings-config-delete-account-text1": "It is a good practice to delete your account from the Streembit network if you don’t use it anymore. Click on the Streembit/Delete account menu item to remove the account from the Streembit network.",
                        "helpitem-settings-config-log-files": "Log files",
                        "helpitem-settings-config-log-files-text1": "Your Streembit system provides vital information using an application log file. The log file is JSON file format, and sits in the application /log directory. You can also open the log file by clicking on the Tools/View logs menu item. Configure the log to “Debug” log level to populate detailed debug messages from the application.",
                        "helpitem-network": "Streembit network",
                        "helpitem_network_connect_public": "Connect to public network",
                        "helpitem-network-connect-public-text1": "Connect to the public Streembit network",
                        "helpitem-network-connect-public-text2": "Click on the “CONNECT TO PUBLIC Streembit” button from the start screen or click on the Streembit/Connect to public network menu item to connect the public Streembit network. The user information view will be initialized. Enter your password and then the application will try to connect to the public Streembit network.",
                        "helpitem_network_connect_private": "Connect to private network",
                        "helpitem_network_connect_private-text1": "Click on the “CONNECT TO PRIVATE Streembit” button from the start screen or click on the Streembit/Connect to private network menu item to connect the a private Streembit hub. The user information view will be initialized. Enter your password and then the application will try to connect to the private Streembit hub.",
                        "helpitem-network-share-keys": "Share your keys",
                        "helpitem-network-share-keys-text1": "Share your public key with your Streembit hub contacts",
                        "helpitem-network-share-keys-text2": "The seed nodes and client nodes of a private Streembit hub identify users by a) validating their PPK signature, b) looking up the account name from a configuration list. That means seeds and clients must know about the public keys and account names of the participants on a the private Streembit hub. Therefore, prior to connecting a private Streembit hub you must share your account details with at least the seed node of private Streembit hub. Typically, you would do this by configuring the seed node configuration file with the list of contacts. (Please refer to the private network readme document at the Streembit Github repository how to create the configuration file for a private Streembit hub.)",
                        "helpitem-network-share-keys-text3": "To get your public key either create a new account or initialize an existing account. Click on the Streembit/New account menu item to create a new account or click on the Streembit/Initialize existing account to use an existing account. Once your account is initialized click on the Tools/Account security info menu item. Your account name and public key will be displayed on the screen. Add this  account name and public key data to the configuration file of private Streembit hub seed.",
                        "helpitem-system": "System",
                        "helpitem-system-clear-database": "Clear database",
                        "helpitem-system-clear-database-text1": "It is essential to clear the database if you are using Streembit on a public computer, for example in an internet café or airport.",
                        "helpitem-system-clear-database-text2": "You can remove all Streembit data from the computer by clicking on the Tools/Clear database menu item. Once the deletion is confirmed the application will erase all configuration, account and contacts data from the computer.",

                        // messages of connection info panel
                        "current-connection-header": "Current Connection Info",
                        "current-connection-account": "Account",
                        "current-connection-transport": "Transport",
                        "current-connection-host": "Host",
                        "current-connection-port": "Port",
                        "current-connection-connsymmkey": "Connsymmkey",
                        "current-connection-pubkey": "Public key",
                        "current-connection-mnemonic": "Mnemonic",

                        // messages for error codes, add an 'errcode_' prefix at the message
                        "errcode_SYSTEM": "System error",
                        "errcode_BADPARAM": "Bad paramater was sent to the procedure",
                        "errcode_INVALID_PAYLOAD": "Invalid payload was sent to the procedure",

                        "errcode_EVENT": "Event handler failed",

                        "errcode_DATABASE": "Database failed",

                        "errcode_HTTP": "HTTP procedure failed",
                        "errcode_HTTP_HANDLEREQUEST": "HTTP handle request failed",
                        "errcode_HTTP_NOWSINFO": "No WS info available at HTTP procedure",
                        "errcode_HTTP_NOWSPEERS": "There are no WS peers available at the HTTP procedure",

                        "errcode_WS": "WebSocket procedure failed",
                        "errcode_WS_ONSEND": "WebSocket onsend handler procedure failed",
                        "errcode_WS_PING": "WebSocket ping procedure failed",
                        "errcode_WS_REGISTER": "WebSocket register client procedure failed",
                        "errcode_WS_DHTPUT": "WebSocket dhtput procedure procedure failed",
                        "errcode_WS_DHTGET": "WebSocket dhtget procedure procedure failed",
                        "errcode_WS_PEERMSG": "WebSocket peer message procedure failed",
                        "errcode_WS_CONTACT_SESSION": "WebSocket session does not exists for contact",
                        "errcode_WS_PEERCOMM": "WebSocket peer communication error",

                        "errcode_UI_CONNECT_TONETWORK": "Error in connecting to Streembit network",
                        "errcode_UI_ON_PEERMSG": "Error in handling message from peer",

                        "errcode_UI_WEBRTC_FILE": "WebRTC file send procedure failed",
                        "errcode_UI_WEBRTC_DATA": "WebRTC data send procedure failed",
                        "errcode_UI_WEBRTC_SCREENSHARE": "WebRTC screen share procedure failed",
                        "errcode_UI_FINDCONTACT": "Finding contact failed",

                        // generic error in case there is no error code
                        "errcode_PROCERROR": "Procedure failed",
                        "errcode_MAX_ERROR_CODE": "0xFFFF",
                        "ERROR": "Application error",

                        // miscellaneous
                        "error-word": "Error",
                        "reason-word": "Reason",
                        "info-word": "Info"
                    }
                },
                de: {
                    translation: {
                        "ERROR": "Anwendungsfehler",
                        "appname-title": "Streembit",
                        "appname-sub-title": "German Decentralized, peer-to-peer, secure communication system for humans and machines",
                        "appload-streembit": "German Load Streembit",
                        "appload-locals": "German Load localization resources",
                        "appload-database": "German Load database",
                        "appload-logger": "German Load application logger",
                        "appload-kademlia": "German Load Kademlia DHT",
                        "lbl-initui-connect": "Verbunden",
                        "lbl-initui-newaccount": "Neues Konto",
                        "lbl-initui-initexisting": "Initialisieren Bestehenden Konto",
                        "lbl-initui-restore": "Wiederherstellung Konto",

                        // errors
                        // TODO

                        // miscellaneous
                        "error-word": "Fehler",
                        "reason-word": "Grund"
                    }
                }
            }
        },
        (err, t) => {
            if (!err) {
                console.log('Local resources loaded');
                resolve();
            }
            else {
                reject(err);
            }
        });
    }); 
}


